Add openfile and websearch
Signed-off-by: Riccardo Finotello <riccardo.finotello@gmail.com>

diff --git a/scripts/attachtmux b/scripts/attachtmux
--- a/scripts/attachtmux
+++ b/scripts/attachtmux
@@ -1,15 +1,14 @@
 #! /usr/bin/env bash
 
 #
-# Attach to existing Tmux session
+# Reattach to Tmux session.
 #
-# The script lists available Tmux sessions and uses rofi/dmenu to give a choice
-# to attach to one of them.
+# Reattach to a previously closed or detached terminal multiplexer session.
 #
 # Author:     Riccardo Finotello
 # E-mail:     riccardo.finotello@gmail.com
 #
-# Copyright:  2019 - Riccardo Finotello and Alessandra Cappati
+# Copyright:  2020 - Riccardo Finotello
 # License:    MIT License
 #
 
@@ -19,69 +18,63 @@
 
 # Show usage
 function show_usage() {
-  USAGE="$(basename $0) [-h]"
-  printf "\n%s\n%s\n" "Usage:" "    $USAGE"
+    USAGE="$(basename $0) [-h] [-n] [-r]"
+    printf "\n%s\n%s\n" "Usage:" "    $USAGE"
 }
 
 # Show help
 function show_help() {
-  show_usage
-
-  printf "\n%s\n\n" "Attach to existing Tmux session"
-  printf "%s\n" "OPTIONS:"
-  printf "%s\n" "    -h         Show this help and exit"
-
-  printf "\n%s\n%s\n\n" \
-    "For bug report and info: riccardo.finotello@gmail.com" \
-    "Copyright (c) 2019 - Riccardo Finotello and Alessandra Cappati - MIT License"
+    show_usage
+  
+    printf "\n%s\n\n" "Reattach to Tmux session."
+    printf "%s\n" "OPTIONS:"
+    printf "%s\n" "    -h         Show this help and exit"
+    printf "%s\n" "    -n         Open a new session"
+    printf "%s\n" "    -r         Reattach to session"
+  
+    printf "\n%s\n%s\n\n" \
+      "For bug report and info: riccardo.finotello@gmail.com" \
+      "Copyright (c) 2020 - Riccardo Finotello - MIT License"
 }
 
+# Check if X11 menu is installed
+[[ -x $(which dmenu) ]] && XMENU=dmenu || exit 1
+
+# Check if Tmux is installed
+[[ -x $(which tmux) ]] && TMUX=tmux || exit 1
+
 # Parse options
-while getopts ":h" opt; do
-  case $opt in
-    h)
-      show_help
-      exit 0
-      ;;
-    \?)
-      printf "%s\n" "Invalid option: -$OPTARG." >&2
-      show_usage
-      exit 1
-      ;;
-    :)
-      printf "%s\n" "-$OPTARG requires an argument." >&2
-      show_usage
-      exit 1
-      ;;
-  esac
+while getopts ":hnr" opt; do
+    case $opt in
+      h)
+        show_help
+        exit 0
+        ;;
+      \?)
+        printf "%s\n" "Invalid option: -$OPTARG." >&2
+        show_usage
+        exit 1
+        ;;
+      n)
+        $TERMINAL -e $TMUX -f $XDG_CONFIG_HOME/tmux/config -2
+        exit 0
+        ;;
+      r)
+        $TMUX list-sessions| grep -i -v 'attached'| \
+              dmenu -i -l 20 -p 'Tmux detached sessions: '| \
+              awk -F': ' '{print $1}'| \
+              xargs -r -I{} $TERMINAL -e tmux attach-session -d -t {}
+        exit 0
+        ;;
+      :)
+        printf "%s\n" "-$OPTARG requires an argument." >&2
+        show_usage
+        exit 1
+        ;;
+    esac
 done
 
 # ------------------------------------
 # COMMANDS AND INFO
 # ------------------------------------
-
-# Check if Tmux is installed
-if [[ ! -z $(which tmux) ]]; then
-  TMUX=$(which tmux)
-else
-  printf "%s\n%s\n%s\n" \
-    "Tmux is not in your PATH" \
-    "You might want to install it. E.g.: sudo pacman -Syu tmux." \
-    "The script will not work without it." >&2
-  exit 1
-fi
-
-# Check if rofi/dmenu is installed
-if [[ ! -z $(which dmenu) ]]; then
-  XMENU=$(which dmenu)
-else
-  printf "%s\n%s\n%s\n" \
-    "There is no X menu installed." \
-    "You might want to install it. E.g.: sudo pacman -Syu dmenu." \
-    "The script cannot work without it." >&2
-  exit 1
-fi
-
-# List detached sessions and ask
-ID=$($TMUX list-sessions | grep -i -v "attached" | $XMENU -i -l 10 -p "Choose session: " | awk -F ': ' '{print $1}')
-$TMUX attach-session -d -t $ID
+[[ -z $* ]] && (show_help && exit 1)
diff --git a/scripts/clipboard b/scripts/clipboard
--- a/scripts/clipboard
+++ b/scripts/clipboard
@@ -11,7 +11,7 @@
 # Author:     Riccardo Finotello
 # E-mail:     riccardo.finotello@gmail.com
 #
-# Copyright:  Alessandra Cappati and Riccardo Finotello - 2019
+# Copyright:  2020 - Riccardo Finotello
 # License:    MIT License
 #
 
@@ -37,39 +37,17 @@ function show_help() {
 
   printf "\n%s\n%s\n\n" \
     "For bug report and info: riccardo.finotello@gmail.com" \
-    "Copyright (c) 2019 - Alessandra Cappati and Riccardo Finotello - MIT License"
+    "Copyright (c) 2020 - Riccardo Finotello - MIT License"
 }
 
 # Check if the clipboard manager is installed
-if [[ ! -z $(which parcellite) ]]; then
-  CLIPBOARD=$(which parcellite)
-else
-  printf "%s\n%s\n%s\n" \
-    "The clipboard manager is not in the PATH." \
-    "You might have to install it. E.g.: sudo pacman -S parcellite." \
-    "The clipboard manager is required for this script to run." >&2
-  exit 1
-fi
+[[ -x $(which parcellite) ]] && CLIPBOARD=parcellite || exit 1
 
 # Check if the Python module to generate QR codes is installed
-if [[ ! -z $(which qr) ]]; then
-  QR=$(which qr)
-else
-  printf "%s\n%s\n%s\n" \
-    "The QR code generator is not in the PATH." \
-    "You might have to install it. E.g.: sudo apt install python-qrenconde." \
-    "Some of the functionalities of this script may be compromised otherwise." >&2
-fi
+[[ -x $(which qr) ]] && QR=qr || exit 1
 
-# Check if the notification client is installed
-if [[ ! -z $(which notify-send) ]]; then
-  NOTIFICATIONS=$(which notify-send)
-else
-  printf "%s\n%s\n%s\n" \
-    "The notification client is not in the PATH." \
-    "You might have to install it. E.g.: sudo apt install ruby-notify." \
-    "Some of the functionalities of this script may be compromised otherwise." >&2
-fi
+# Define the image viewer
+[[ -x $(which feh) ]] && IMG=feh || IMG=xdg-open
 
 # Show clipboard content
 function show_clipboard() {
@@ -108,7 +86,7 @@ function send_notification() {
       ;;
   esac
 
-  $NOTIFICATIONS -a "Clipboard" "$TITLE" "$(show_clipboard $ARG)"
+  notify-send "$TITLE" "$(show_clipboard $ARG)"
 }
 
 function show_notification() {
@@ -129,19 +107,9 @@ function show_notification() {
 function choose_img_viewer() {
   ARG=${1:0:1}
 
-  if [[ ! -z $DISPLAY ]]; then
-    if [[ ! -z $(which feh) ]]; then
-      $CLIPBOARD -$ARG | $QR | $(which feh) -Z -
-    elif [[ ! -z $(which sxiv ) ]]; then
-      TMPFILE=$(mktemp /tmp/qr_XXXXXXXXX.png)
-      $CLIPBOARD -$ARG | $QR > $TMPFILE
-      $(which sxiv) $TMPFILE
-    else
-      $CLIPBOARD -$ARG | $QR
-    fi
-  else
-    $CLIPBOARD -$ARG | $QR
-  fi
+  [[ $DISPLAY ]] \
+      && ($CLIPBOARD -$ARG| $QR| $IMG -Z -) \
+      || ($CLIPBOARD -$ARG| $QR)
 }
 
 function show_qr() {
@@ -171,24 +139,14 @@ while getopts ":hc:n:q:" opt; do
       exit 0
       ;;
     n)
-      if [[ ! -z $NOTIFICATIONS ]] && [[ ! -z $DISPLAY ]]; then
-        show_notification $OPTARG
-        exit 0
-      else
-        printf "%s\n" \
-          "It is impossible to show notifications at this time." >&2
-        exit 1
-      fi
+      [[ $DISPLAY ]] \
+          && (show_notification $OPTARG && exit 0) \
+          || (printf "%s\n" "Unable to show notifications." >&2 && exit 1)
       ;;
     q)
-      if [[ ! -z $QR ]]; then
-        show_qr $OPTARG
-        exit 0
-      else
-        printf "%s\n" \
-          "It is impossible to encode a QR code at this time." >&2
-        exit 1
-      fi
+      [[ $QR ]] \
+          && (show_qr $OPTARG && exit 0) \
+          || (printf "%s\n" "Unable to encode a QR code." >&2 && exit 1)
       ;;
     \?)
       printf "%s\n" "Invalid option: -$OPTARG is not an option." >&2
@@ -207,7 +165,9 @@ while getopts ":hc:n:q:" opt; do
   esac
 done
 
-if [[ -z $1 ]]; then
-  show_help
-  exit 1
-fi
+# ------------------------------------
+# COMMANDS AND INFO
+# ------------------------------------
+[[ -z $* ]] && (show_help && exit 1)
+
+# vim: ft=sh
diff --git a/scripts/dbookmarks b/scripts/dbookmarks
--- a/scripts/dbookmarks
+++ b/scripts/dbookmarks
@@ -1,15 +1,14 @@
 #! /usr/bin/env bash
 
 #
-# Open bookmarked URLs.
+# Open bookmarks.
 #
-# This script reads and edits a bookmark file and has the user select and open
-# one of them in a browser session.
+# Read bookmarks list and open links in a browser window.
 #
 # Author:     Riccardo Finotello
 # E-mail:     riccardo.finotello@gmail.com
 #
-# Copyright:  2019 - Riccardo Finotello and Alessandra Cappati
+# Copyright:  2020 - Riccardo Finotello
 # License:    MIT License
 #
 
@@ -19,132 +18,64 @@
 
 # Show usage
 function show_usage() {
-  USAGE="$(basename $0) [-h] [-e] [-u URL && -n NAME]"
-  printf "\n%s\n%s\n" "Usage:" "    $USAGE"
+    USAGE="$(basename $0) [-h] [-e] [-m]"
+    printf "\n%s\n%s\n" "Usage:" "    $USAGE"
 }
 
 # Show help
 function show_help() {
-  show_usage
-
-  printf "\n%s\n\n" "Open bookmarked URLs."
-  printf "%s\n" "OPTIONS:"
-  printf "%s\n" "    -h         Show this help and exit"
-  printf "%s\n" "    -e         Edit the bookmark file"
-  printf "%s\n" "    -m         Open selection menu"
-  printf "%s\n" "    -u URL     add URL of the bookmark"
-  printf "%s\n" "    -n NAME    NAME of the new bookmark (use with -u)"
-
-  printf "\n%s\n%s\n\n" \
-    "For bug report and info: riccardo.finotello@gmail.com" \
-    "Copyright (c) 2019 - Riccardo Finotello and Alessandra Cappati - MIT License"
+    show_usage
+  
+    printf "\n%s\n\n" "Open bookmarked URLs."
+    printf "%s\n" "OPTIONS:"
+    printf "%s\n" "    -h         Show this help and exit"
+    printf "%s\n" "    -e         Edit the bookmark file"
+    printf "%s\n" "    -m         Open selection menu"
+  
+    printf "\n%s\n%s\n\n" \
+      "For bug report and info: riccardo.finotello@gmail.com" \
+      "Copyright (c) 2020 - Riccardo Finotello - MIT License"
 }
 
 # Check if the X11 menu is installed
-if [[ -x $(which dmenu) ]]; then
-  XMENU=$(which dmenu)
-else
-  printf "%s\n%s\n%s\n" \
-    "The X menu is not in your path." \
-    "You might want to add it. E.g.: sudo pacman -Syu dmenu" \
-    "The script will not work without it." >&2
-  exit 1
-fi
+[[ -x $(which dmenu) ]] && XMENU=dmenu || exit 1
 
-# Choose the configuration file
-if [[ -f $HOME/.config/dbookmarks/bookmarks.list ]]; then
-  CONFIG=$HOME/.config/dbookmarks/bookmarks.list
-elif [[ -f $(xdg-user-dir CONFIG)/dbookmarks/bookmarks.list ]]; then
-  CONFIG=$(xdg-user-dir CONFIG)/dbookmarks/bookmarks.list
-else
-  mkdir -p $HOME/.config/dbookmarks 2> /dev/null
-  touch $HOME/.config/dbookmarks/bookmarks.list
-  CONFIG=$HOME/.config/dbookmarks/bookmarks.list
-fi
+# Check if browser is set
+[[ -n $BROWSER ]] && URLOPEN=$BROWSER || URLOPEN=xdg-open
 
-# Function to edit the file
-function edit_file() {
-  if [[ -x $(which vim) ]]; then
-    $(which vim) $CONFIG
-  elif [[ -x $(which emacs) ]]; then
-    $(which emacs) $CONFIG
-  elif [[ -x $(which xdg-open) ]]; then
-    $(which xdg-open) $CONFIG
-  else
-    $(which nano) $CONFIG
-  fi
-}
-
-# Open selection menu
-function selection_menu() {
-  if [[ -n $XMENU ]]; then
-    CHOICE=$(awk -F';' '{print $1 " (" $2 ")"}' $CONFIG | \
-      sort | \
-      $XMENU -i -l 15 -p "Select URL" | \
-      sed 's/.*(\(.*\)).*/\1/g' )
-  fi
-
-  if [[ -n $CHOICE ]]; then
-    if [[ -n $BROWSER ]]; then
-      $BROWSER $CHOICE
-    elif [[ -x $(which xdg-open) ]]; then
-      $(which xdg-open) $CHOICE
-    else
-      printf "%s\n" $CHOICE
-    fi
-  fi
-}
+# Choose the bookmarks list
+LIST=$XDG_DATA_HOME/dbookmarks/bookmarks.txt
+[[ ! -f $LIST ]] && (mkdir -p $XDG_DATA_HOME/dbookmarks 2> /dev/null \
+                     && touch $LIST)
 
 # Parse options
-while getopts ":hemu:n:" opt; do
-  case $opt in
-    h)
-      show_help
-      exit 0
-      ;;
-    e)
-      edit_file
-      exit 0
-      ;;
-    m)
-      selection_menu
-      exit 0
-      ;;
-    u)
-      URL=$OPTARG
-      ;;
-    n)
-      NAME=$OPTARG
-      ;;
-    \?)
-      printf "%s\n" "Invalid option: -$OPTARG." >&2
-      show_usage
-      exit 1
-      ;;
-    :)
-      printf "%s\n" "-$OPTARG requires an argument." >&2
-      show_usage
-      exit 1
-      ;;
-  esac
+while getopts ":hem" opt; do
+    case $opt in
+      h)
+        show_help
+        exit 0
+        ;;
+      e)
+        [[ $EDITOR ]] && $EDITOR $LIST || xdg-open $LIST
+        exit 0
+        ;;
+      m)
+        cat $LIST| sort| column -t -s'^^^'| \
+            $XMENU -i -l 20 -p 'Web bookmarks: '| awk '{print $NF}'| \
+            xargs -r $BROWSER --new-window
+        exit 0
+        ;;
+      \?)
+        printf "%s\n" "Invalid option: -$OPTARG." >&2
+        show_usage
+        exit 1
+        ;;
+      :)
+        printf "%s\n" "-$OPTARG requires an argument." >&2
+        show_usage
+        exit 1
+        ;;
+    esac
 done
 
-# ------------------------------------
-# COMMANDS AND INFO
-# ------------------------------------
-
-if [[ -z $1 ]]; then
-  show_help
-  exit 1
-fi
-
-if [[ ! -n $URL ]]; then
-  printf "%s\n" "Missing URL!"
-  exit 1
-fi
-
-if [[ ! -n $NAME ]]; then
-  printf "%s\n" "Missing name/description!"
-fi
-
-echo "$NAME;$URL" >> $CONFIG
+# vim: ft=sh
diff --git a/scripts/dman b/scripts/dman
--- a/scripts/dman
+++ b/scripts/dman
@@ -1,15 +1,14 @@
 #! /usr/bin/env bash
 
 #
-# Show dmenu/rofi list of all man pages and display them.
+# Select and display man page.
 #
-# Search through the Linux man pages and display a X menu selector. Then show
-# the man page.
+# Search and select for a man page and display it as PDF.
 #
 # Author:     Riccardo Finotello
 # E-mail:     riccardo.finotello@gmail.com
 #
-# Copyright:  2019 - Riccardo Finotello and Alessandra Cappati
+# Copyright:  2020 - Riccardo Finotello
 # License:    MIT License
 #
 
@@ -19,84 +18,57 @@
 
 # Show usage
 function show_usage() {
-  USAGE="$(basename $0) [-h]"
-  printf "\n%s\n%s\n" "Usage:" "    $USAGE"
+    USAGE="$(basename $0) [-h]"
+    printf "\n%s\n%s\n" "Usage:" "    $USAGE"
 }
 
 # Show help
 function show_help() {
-  show_usage
-
-  printf "\n%s\n\n" "Show dmenu list of all man pages and display them."
-  printf "%s\n" "OPTIONS:"
-  printf "%s\n" "    -h         Show this help and exit"
-
-  printf "\n%s\n%s\n\n" \
-    "For bug report and info: riccardo.finotello@gmail.com" \
-    "Copyright (c) 2019 - Riccardo Finotello and Alessandra Cappati - MIT License"
+    show_usage
+  
+    printf "\n%s\n\n" "Select and display man page."
+    printf "%s\n" "OPTIONS:"
+    printf "%s\n" "    -h         Show this help and exit"
+  
+    printf "\n%s\n%s\n\n" \
+      "For bug report and info: riccardo.finotello@gmail.com" \
+      "Copyright (c) 2020 - Riccardo Finotello - MIT License"
 }
 
 # Parse options
 while getopts ":h" opt; do
-  case $opt in
-    h)
-      show_help
-      exit 0
-      ;;
-    \?)
-      printf "%s\n" "Invalid option: -$OPTARG." >&2
-      show_usage
-      exit 1
-      ;;
-    :)
-      printf "%s\n" "-$OPTARG requires an argument." >&2
-      show_usage
-      exit 1
-      ;;
-  esac
+    case $opt in
+      h)
+        show_help
+        exit 0
+        ;;
+      \?)
+        printf "%s\n" "Invalid option: -$OPTARG." >&2
+        show_usage
+        exit 1
+        ;;
+      :)
+        printf "%s\n" "-$OPTARG requires an argument." >&2
+        show_usage
+        exit 1
+        ;;
+    esac
 done
 
 # Check if dmenu/rofi are installed
-if [[ -x $(which dmenu) ]]; then
-  XMENU=$(which dmenu)
-else
-  printf "%s\n%s\n%s\n" \
-    "No X11 menu have been found." \
-    "You should consider installing one. E.g.: sudo pacman -S dmenu." \
-    "The script will not continue without it."
-  exit 1
-fi
+[[ -x $(which dmenu) ]] && XMENU=dmenu || exit 1
 
 # Check if a PDF reader is installed
-if [[ -x $(which zathura) ]]; then
-  PDFOPEN=$(which zathura)
-elif [[ -x $(which mupdf) ]]; then
-  PDFOPEN=$(which mupdf)
-elif [[ -x $(which evince) ]]; then
-  PDFOPEN=$(which evince)
-elif [[ -x $(which okular) ]]; then
-  PDFOPEN=$(which okular)
-elif [[ -x $(which xdg-open) ]]; then
-  PDFOPEN=$(which xdg-open)
-else
-  printf "%s\n%s\n%s\n" \
-    "No PDF reader has not been found." \
-    "You should consider installing one. E.g.: sudo pacman -S mupdf." \
-    "The script will not continue without it."
-  exit 1
-fi
+[[ $READER ]] && PDFOPEN=$READER || PDFOPEN=xdg-open
 
 # ------------------------------------
 # COMMANDS AND INFO
 # ------------------------------------
+MANPAGE=$(apropos .| sort| sed 's/[)] *- /)^^^/'| column -t -s'^^^'| \
+          $XMENU -i -l 20 -p 'Man pages: '| awk '{print $1}')
 
-MANPAGE=$(man -k . | $XMENU -i -l 10 -p "Choose the man page" | awk '{print $1}')
-
-if [[ $MANPAGE ]]; then
-  TMP=$(mktemp /tmp/dman_XXXXXX.pdf)
-  man -Tpdf $MANPAGE > $TMP
-  $PDFOPEN $TMP
-  rm $TMP
-fi
+[[ $MANPAGE ]] && (man -Tpdf $MANPAGE| $READER -) || exit 1
 
 exit 0
+
+# vim: ft=sh
