Add redirection to stderr where needed. Power management now relies on ACPI instead of UPower
Signed-off-by: Riccardo Finotello <riccardo.finotello@gmail.com>

diff --git a/scripts/connectivity b/scripts/connectivity
--- a/scripts/connectivity
+++ b/scripts/connectivity
@@ -48,7 +48,7 @@ else
   printf "%s\n%s\n%s\n" \
     "The NetworkManager command line interface is not in the PATH." \
     "You might have to install it. E.g.: sudo apt install network-manager." \
-    "The NetworkManager CLI is required for this script to run."
+    "The NetworkManager CLI is required for this script to run." >&2
   exit 1
 fi
 
@@ -88,7 +88,7 @@ else
   printf "%s\n%s\n%s\n" \
     "The notification client is not in the PATH." \
     "You might have to install it. E.g.: sudo apt install ruby-notify." \
-    "Some of the functionalities of this script may be compromised otherwise."
+    "Some of the functionalities of this script may be compromised otherwise." >&2
 fi
 
 # Clickable block when using i3blocks in i3wm
@@ -148,7 +148,7 @@ function show_ip() {
     INFO=$(which ifconfig)
   else
     printf "%s\n" \
-      "Unable to show IP address at this time."
+      "Unable to show IP address at this time." >&2
     exit 1
   fi
 
@@ -179,7 +179,7 @@ function toggle_wifi_state() {
       $NMCLI radio wifi on
       ;;
     *)
-      printf "%s\n" "Invalid STATUS: '$1' is not a valid status."
+      printf "%s\n" "Invalid STATUS: '$1' is not a valid status." >&2
       exit 1
       ;;
   esac
@@ -241,7 +241,7 @@ case $1 in
     exit 0
     ;;
   *)
-    printf "%s\n" "Invalid COMMAND: $1 is not a valid argument."
+    printf "%s\n" "Invalid COMMAND: $1 is not a valid argument." >&2
     show_help
     exit 1
     ;;
diff --git a/scripts/partmount b/scripts/partmount
--- a/scripts/partmount
+++ b/scripts/partmount
@@ -22,7 +22,7 @@
 
 # Show usage
 function show_usage() {
-  USAGE="$(basename $0) [-h] [-b CMD]"
+  USAGE="$(basename $0) [-h] [-b CMD] [-a CMD]"
   printf "\n%s\n%s\n" "Usage:" "    $USAGE"
 }
 
@@ -53,7 +53,7 @@ else
   printf "%s\n%s\n%s\n" \
     "The X11 menu is not in the PATH." \
     "You might want to install it. E.g.: sudo apt install rofi." \
-    "The script entirely relies on its presence."
+    "The script entirely relies on its presence." >&2
   exit 1
 fi
 
@@ -64,7 +64,7 @@ else
   printf "%s\n%s\n%s\n" \
     "The notification client is not in the PATH." \
     "You might have to install it. E.g.: sudo apt install ruby-notify." \
-    "Some of the functionalities of this script may be compromised otherwise."
+    "Some of the functionalities of this script may be compromised otherwise." >&2
 fi
 
 # Check presence of lsblk command and MTP tools
@@ -72,7 +72,7 @@ if [[ ! -z $(which lsblk) ]]; then
   LSBLK=$(which lsblk)
 else
   printf "%s\n" \
-    "We could not find a way to display available partitions."
+    "We could not find a way to display available partitions." >&2
   exit 1
 fi
 
@@ -82,7 +82,7 @@ else
   printf "%s\n%s\n%s\n" \
     "We could not find a way to display available partitions." \
     "You might want to install mtp-detect. E.g.: sudo apt install mtp-detect." \
-    "Some of the functionalities will not be available."
+    "Some of the functionalities will not be available." >&2
 fi
 
 if [[ ! -z $(which jmtpfs) ]]; then
@@ -91,7 +91,7 @@ else
   printf "%s\n%s\n%s\n" \
     "We could not find a way to mount Android devices." \
     "You might want to install jmtpfs. E.g.: sudo apt install jmtpfs." \
-    "The script will not work without it."
+    "The script will not work without it." >&2
   exit 1
 fi
 
@@ -102,7 +102,7 @@ else
   printf "%s\n%s\n%s\n" \
     "The JSON parser is not in the PATH." \
     "You might have to install it. E.g.: sudo apt install jq" \
-    "The JSON parser JQ is required for this script to work."
+    "The JSON parser JQ is required for this script to work." >&2
   exit 1
 fi
 
@@ -115,14 +115,15 @@ else
   printf "%s\n%s\n%s\n" \
     "We could not find a file manager." \
     "You might want to install one. E.g.: sudo apt ranger." \
-    "Some of the functionalities might be compromised."
+    "Some of the functionalities might be compromised." >&2
 fi
 
 # Display block devices
 function display_block_devices() {
   DEVS=$($LSBLK -pJo "name,size,label,mountpoint,rm")
+  $LSBLK
   MOUNTABLE=$(echo $DEVS | \
-    $JQ '.blockdevices | map(select( .rm == "1" ))')
+    $JQ '.blockdevices | map(select( .rm == "true" ))')
   LENGTH=$(echo $MOUNTABLE | $JQ 'length')
 
   TOTALCHILDREN=0
@@ -133,7 +134,7 @@ function display_block_devices() {
     elif [[ $1 == "unmount" ]]; then
       CHILD=$(echo $MOUNTABLE | $JQ ".[$(( counter - 1 ))].children | map(select( .mountpoint != null ))")
     else
-      printf "%s\n" "Invalid argument: $1 is not a valid command."
+      printf "%s\n" "Invalid argument: $1 is not a valid command." >&2
       exit 1
     fi
     CHILDLENGTH=$(echo $CHILD | $JQ 'length')
@@ -267,7 +268,7 @@ while getopts ":hb:a:" opt; do
           exit 0
           ;;
         *)
-          printf "%s\n" "Invalid argument: $OPTARG is not a good command."
+          printf "%s\n" "Invalid argument: $OPTARG is not a good command." >&2
           exit 1
           ;;
       esac
@@ -283,7 +284,7 @@ while getopts ":hb:a:" opt; do
           exit 0
           ;;
         *)
-          printf "%s\n" "Invalid argument: $OPTARG is not a good command."
+          printf "%s\n" "Invalid argument: $OPTARG is not a good command." >&2
           exit 1
           ;;
       esac
diff --git a/scripts/power b/scripts/power
--- a/scripts/power
+++ b/scripts/power
@@ -35,7 +35,7 @@ function show_help() {
   printf "%s\n" "    -h            Show this help and exit"
   printf "%s\n" "    -m            Shows an interactive menu"
   printf "%s\n" "    -c COMMAND    Execute COMMAND and exit"
-  printf "%s\n" "    -n STATUS     Chenge the status of the notifications"
+  printf "%s\n" "    -n STATUS     Change the status of the notifications"
   printf "\n%s\n" "COMMAND:"
   printf "%s\n" "    l or lock     Lock the screen"
   printf "%s\n" "    q or logout   Log out from the current session"
@@ -61,13 +61,13 @@ if [[ ! -z $(which dunst) ]]; then
     printf "%s\n%s\n%s\n" \
       "The notification client is not in the PATH." \
       "You might have to install it. E.g.: sudo apt install ruby-notify." \
-      "Some of the functionalities of this script may be compromised otherwise."
+      "Some of the functionalities of this script may be compromised otherwise." >&2
   fi
 else
   printf "%s\n%s\n%s\n" \
     "The default notification client is not installed." \
     "You might have to install it. E.g.: sudo apt install dunst." \
-    "Some of the functionalities of this script may be compromised otherwise."
+    "Some of the functionalities of this script may be compromised otherwise." >&2
 fi
 
 # Check if systemctl is in the PATH
@@ -77,7 +77,7 @@ else
   printf "%s\n%s\n%s\n" \
     "Systemctl is not in the PATH." \
     "Systemctl is a critical component of this script." \
-    "The script will not work unless systemctl is in the path."
+    "The script will not work unless systemctl is in the path." >&2
   exit 1
 fi
 
@@ -88,7 +88,7 @@ else
   printf "%s\n%s\n%s\n" \
     "The default screen locker is not in the PATH." \
     "You might have to install it. E.g.: sudo apt install i3lock." \
-    "Some of the functionalities of this script may be compromised otherwise."
+    "Some of the functionalities of this script may be compromised otherwise." >&2
 fi
 
 # Check if the exit script is installed
@@ -98,7 +98,7 @@ else
   printf "%s\n%s\n%s\n" \
     "The default window manager is i3." \
     "We have not detected the correct logout script (i3-msg)." \
-    "Some of the functionalities of this script may be compromised."
+    "Some of the functionalities of this script may be compromised." >&2
 fi
 
 # Check if the xmenu script is installed
@@ -110,7 +110,7 @@ else
   printf "%s\n%s\n%s\n" \
     "The xmenu script is not in the PATH." \
     "You might have to install it. E.g.: sudo apt install rofi." \
-    "Some of the functionalities of this script may be compromised otherwise."
+    "Some of the functionalities of this script may be compromised otherwise." >&2
 fi
 
 # Stop/start notifications
@@ -144,7 +144,7 @@ function screen_lock() {
       *)
         printf "%s\n%s\n" \
           "Invalid argument: '$1' is not a valid argument." \
-          "You must choose between 'fork' and 'not-fork'."
+          "You must choose between 'fork' and 'not-fork'." >&2
         ;;
     esac
   fi
@@ -202,7 +202,7 @@ function parse_command() {
       poweroff_system
       ;;
     *)
-      printf "%s\n" "Invalid COMMAND: '$1' is not a valid argument."
+      printf "%s\n" "Invalid COMMAND: '$1' is not a valid argument." >&2
       show_help
       exit 1
       ;;
@@ -243,7 +243,7 @@ function show_menu() {
         poweroff_system
         ;;
       *)
-        printf "%s\n" "Invalid argument: '$RESP' is not a valid command."
+        printf "%s\n" "Invalid argument: '$RESP' is not a valid command." >&2
         ;;
     esac
   fi
@@ -280,7 +280,7 @@ function toggle_notifications() {
         esac
         ;;
       *)
-        printf "%s\n" "Invalid argument: '$1' is not a valid STATUS"
+        printf "%s\n" "Invalid argument: '$1' is not a valid STATUS" >&2
         show_help
         exit 1
         ;;
diff --git a/scripts/printer b/scripts/printer
--- a/scripts/printer
+++ b/scripts/printer
@@ -52,7 +52,7 @@ else
   printf "%s\n%s\n%s\n" \
     "lpstat and lp are not in the PATH." \
     "You might have to install it. E.g.: sudo apt install lpr." \
-    "This script cannot work without them."
+    "This script cannot work without them." >&2
   exit 1
 fi
 
@@ -65,7 +65,7 @@ else
   printf "%s\n%s\n%s\n" \
     "No X11 menu have been detected." \
     "You might take into consideration installing one. E.g.: sudo apt install rofi." \
-    "Some of the functionalities will be compromised."
+    "Some of the functionalities will be compromised." >&2
 fi
 
 # DEFAULTS (where necessary) and info
@@ -92,7 +92,7 @@ while getopts ":hmP:dDn:p:l" opt; do
       if [[ -z $DUPLEX ]]; then
         DUPLEX="Long edge"
       else
-        printf "%s\n" "DUPLEX cannot be set twice: invalid argument."
+        printf "%s\n" "DUPLEX cannot be set twice: invalid argument." >&2
         show_usage
         exit 1
       fi
@@ -101,7 +101,7 @@ while getopts ":hmP:dDn:p:l" opt; do
       if [[ -z $DUPLEX ]]; then
         DUPLEX="Short edge"
       else
-        printf "%s\n" "DUPLEX cannot be set twice: invalid argument."
+        printf "%s\n" "DUPLEX cannot be set twice: invalid argument." >&2
         show_usage
         exit 1
       fi
@@ -140,15 +140,15 @@ fi
 # Missing file exception
 function missing_file() {
   if [[ -z $FILE ]]; then
-    printf "%s\n" "FILE is missing."
+    printf "%s\n" "FILE is missing." >&2
     show_usage
     exit 1
   elif [[ $FILE == -* ]]; then
-    printf "%s\n" "$FILE is not a good file: invalid name."
+    printf "%s\n" "$FILE is not a good file: invalid name." >&2
     show_usage
     exit 1
   elif [[ ! -f $(readlink -f $FILE 2> /dev/null) ]]; then
-    printf "%s\n" "$FILE is not a good file: file does not exist."
+    printf "%s\n" "$FILE is not a good file: file does not exist." >&2
     show_usage
     exit 1
   fi
@@ -157,10 +157,10 @@ function missing_file() {
 # Print function
 function print_content() {
   if [[ $PRINTERS != *$PRINTER* ]]; then
-    printf "%s\n" "$PRINTER is not installed in the system: invalid argument."
+    printf "%s\n" "$PRINTER is not installed in the system: invalid argument." >&2
     exit 1
   elif [[ -z $PRINTER ]]; then
-    printf "%s\n" "You must select a printer to use."
+    printf "%s\n" "You must select a printer to use." >&2
     exit 1
   else
     LP+=" -d $PRINTER"
@@ -179,7 +179,7 @@ function print_content() {
         LP+=" -o sides=two-sided-short-edge"
         ;;
       *)
-        printf "%s\n" "Invalid argument: $DUPLEX is not a valid command."
+        printf "%s\n" "Invalid argument: $DUPLEX is not a valid command." >&2
         ;;
     esac
   fi
diff --git a/scripts/weather b/scripts/weather
--- a/scripts/weather
+++ b/scripts/weather
@@ -72,7 +72,7 @@ else
   printf "%s\n%s\n%s\n" \
     "curl is not in the PATH." \
     "You might have to install it. E.g.: sudo apt install curl" \
-    "curl is required for this script to work."
+    "curl is required for this script to work." >&2
   exit 1
 fi
 
@@ -82,7 +82,7 @@ else
   printf "%s\n%s\n%s\n" \
     "The JSON parser is not in the PATH." \
     "You might have to install it. E.g.: sudo apt install jq" \
-    "The JSON parser JQ is required for this script to work."
+    "The JSON parser JQ is required for this script to work." >&2
   exit 1
 fi
 
@@ -124,7 +124,7 @@ function json_report() {
     "shower rain")
       ICON="\ue309"
       ;;
-    rain)
+    rain|"light rain")
       ICON="\ue308"
       ;;
     thunderstorm)
@@ -150,12 +150,12 @@ function json_report() {
         echo -e "$NAME: $TEMP°C ($MAIN) $ICON"
         ;;
       *)
-        printf "%s\n" "Invalid argument: unable to parse weather info."
+        printf "%s\n" "Invalid argument: unable to parse weather info." >&2
         exit 1
         ;;
     esac
   else
-    printf "%s\n" "$ICON"
+    printf "%s\n" "$ICON" >&2
     exit 1
   fi
 }
